---
title: "Covid-19"
author: "Siming Yan"
date:   "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: spacelab
    keep_md: true
    toc: yes
    toc_float: true
    highlight: haddock
    
---

<html>
<style> 
div.bgm { background-color:#e6fff0; border-radius: 7px; padding: 10px;} 
.ans {
  color: purple;
  font-weight: bold;
}
#main { 
    color: #2cb061; 
}
</style>

<div class = "bgm">

<ul id="main">


```{r setup, echo=FALSE, cache=FALSE, include = F}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
knitr::opts_chunk$set(
	fig.width = 7,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	comment = NA,
	dpi = 300,
	prompt = FALSE,
	tidy = TRUE
)
opts_knit$set(width=75)
# knitr::opts_chunk$set()
options(digits=5)
options(scipen=5)
knitr::opts_chunk$set(warning = F, message=F)

```

### set
 
```{r setup2, include=FALSE}

library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(stargazer)
library(tidyverse)
# library(car)
library(formatR)
# library(plm)
# library(lfe)
library(data.table)
# library(mlogit)
# library(lmtest) #for coeftest() and bptest().
# library(broom) #for glance() and tidy()
# library(RCurl)# For the robust SE method 1
# library(sandwich)
library(texreg) 
library(mice) #check NA
# library(MatchIt)
library(ggthemes)
library(RColorBrewer)
library(readxl)
library(openxlsx)
library(zoo)
library(pinyin)
library(ggthemr)
library(kableExtra)
library(plotly)
```

```{r functions, warning=F, message=F, include = F}
kbt <- function(...){
  knitr::kable(..., format.args = list(big.mark = ',', scientific = F)) %>%
    kableExtra::kable_styling(c("striped", "hover", "condensed"),
                               full_width = F,
                               position = "center",
                               row_label_position = "c") %>%
   row_spec(0, bold = T, color = "white", background = "#004d1f")
}

gpt <- function(...){
  ggplot2::ggplot(...) + 
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
      plot.subtitle = element_text(face = "italic", size = 12, hjust = 0.5), 
      axis.text.x = element_text(angle = 0, hjust = 0.5))
}

stg <- function(...){
  stargazer::stargazer(..., 
          type = "text",
          # style = "qje",
          # title = "daily_kwh ~ post:encouraged|customer_id + no.bill|0|customer_id",
          keep.stat = c("n", "ser"),
          digits = 5)
}

gpt_area <- function(in_data, in_x, in_y, in_times, heading, heading_x,heading_y){
  gpt(in_data) +
  # geom_point(aes(x = in_x, 
  #              y = in_times*in_y), 
  #          alpha = I(.8)) +
  # geom_line(aes(x = in_x, 
  #              y = in_times*in_y,
  #              group = 1)) +
  geom_bar(aes(x = in_x, 
               weight = in_y,
               alpha = I(.9))) +
  theme(axis.text.x = element_text(angle = 0, hjust = .6)) +
  geom_text(data = in_data,
            aes(x = in_x,
                y = in_y,
                label= in_y),
            size = 5, 
            vjust = -0.2) +
  labs(title  = heading,
       x = heading_x,
       y = heading_y) +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25))
}

mod_stargazer <- function(output.file, ...) {
  output <- capture.output(stargazer(...))
  cat(paste(output, collapse = "\n"), "\n", file=output.file, append=F)
}

ggthemr('light',type = 'outer')

```




#--------------------------------------------

## 1. data_pp(16-19)


```{r}

library(coronavirus)
# run_app(virus)
# ggthemr('light',type = 'outer')
```


```{r}
covid <- coronavirus %>%
  filter(country == "China", type == "confirmed")
covid_sx <- covid %>% filter(province == "Shanxi")

```


```{r}
ggplot(covid) +
 aes(x = date, fill = country, colour = cases, group = country, weight = cases) +
 geom_bar(position = "dodge") +
 scale_fill_brewer(palette = "RdGy") +
 scale_color_distiller(palette = "RdGy") 

```


#--------------------------------------------
## 2. covid plots

```{r}
covid <- covid %>% 
  mutate(date = ymd(date)) %>% 
  mutate_at(vars(date), funs(year, month, day))

confirm_plt <- aggregate(cases~month, covid, sum)

gpt(confirm_plt)+
  aes(x = month, y = cases)+
  geom_col()+
  geom_text(data = confirm_plt,
            aes(x = month,
                y =  cases,
                label= cases),
            vjust = -0.2)


gpt_china_covid_case <- gpt_area(confirm_plt, 
                                 confirm_plt$month, 
                                 confirm_plt$cases, 
                                 1, 
                                 "Exsisting cases in China Mainland", 
                                 "month", 
                                 "sum") + 
  scale_x_continuous(n.breaks = 7)

ggsave(filename = "../report/covid_china_case.png", plot = gpt_china_covid_case, width = 12)
# #--------------------------------------------

gpt_china_covid_case 
#   geom_point(data = pp_data, x = month, y)
```

#--------------------------------------------

```{r}
pp_yrm_s.complete_plt <- pp_data %>% group_by(month, as.factor(year)) %>% summarise(sum(complete)) %>% 
  rbind()

pt1 <- pp_yrm_s.complete_plt[pp_yrm_s.complete_plt$`as.factor(year)` == "20",]
pt1[7,] <- pt1[6,]
pt1[7,1] <- 7
pt1[7,3] <- 301.1704-53.964
plt1 <- cbind(confirm_plt, pt1)
plt1 <- plt1[,-1]


china_covid_el_gen <- gpt_area(plt1, 
                               confirm_plt$month, 
                               confirm_plt$cases, 
                               1, 
                               "Exsisting cases in China Mainland", 
                               "month", 
                               "sum") + 
  geom_point(aes(x = month, y = `sum(complete)` * 100), color = "red") +
  geom_line(aes(x = month, y = `sum(complete)` * 100), color = "purple") +
  geom_text(data = plt1,
            aes(x = month,
                y = `sum(complete)` * 100 ,
                label= `sum(complete)`),
            vjust = -0.2,
            size = 6) +
  scale_x_continuous(n.breaks = 7) 
#--------------------------------------------
china_covid_el_gen
ggsave(filename = "../report/covid_el-gen_china.png", plot = china_covid_el_gen, width = 12)

```

```{r}
covid_sx <- covid_sx %>% group_by(month) %>% summarise(sum(cases)) %>% cbind(pt1)
covid_sx <- covid_sx[,-3]

ggthemr('light',type = 'outer')

shanxi_covid_el_gen <- gpt_area(covid_sx, 
                                covid_sx$month, 
                                covid_sx$`sum(cases)`, 
                                1, 
                                "Exsisting cases in Shanxi Province", 
                                "month", 
                                "sum") + 
  geom_point(aes(x = month, y = `sum(complete)` ), color = "red") +
  geom_line(aes(x = month, y = `sum(complete)` ), color = "purple") +
  geom_text(data = covid_sx,
            aes(x = month,
                y = `sum(complete)` ,
                label= `sum(complete)`),
            vjust = -0.2,
            size = 5) +
  scale_x_continuous(n.breaks = 7) 
shanxi_covid_el_gen

#-------------------------------------------
ggsave(filename = "../report/covid_el-gen_shanxi.png", plot = shanxi_covid_el_gen, width = 12)
```





#--------------------------------------------

```{r}
# p1 <- ggplot(pp_yrm_s.complete_plt) +
#  aes(x = month, y = `sum(complete)`, colour = `as.factor(year)`) +
#  geom_line(size = .5L) +
#  scale_color_hue() +
#  theme_minimal() + 
#  scale_x_continuous(n.break = 12)
# p1 
```


```{r}
confirm_plt <- aggregate(cases~month, covid, sum)
plt2 <- merge(confirm_plt, pp_yrm_s.complete_plt, by = "month")

ggplot(plt2) +
 aes(x = month) +
 geom_line(aes(y = plt2$`sum(complete)`*915), 
     fill = plt2$`sum(complete)`, 
     colour = plt2$`as.factor(year)`, 
     group = plt2$`as.factor(year)`, size = 1L) +
 scale_fill_gradient() +
 scale_color_hue() +
 theme_minimal() +
  geom_bar(aes(x = month, weight = cases), alpha = I(.4))
```



#--------------------------------------------

## 3. big5

```{r}
pp_data$big_five %>% table
# 9594+2766 
# 0     1 
df_big5_year_comp <- pp_data %>% group_by(big_five, year, month) %>% summarise(mean.com = mean(complete),
                                                                               mean.cap = mean(capacity))

# df_big5_year_comp <- df_big5_year_comp[-c(1,6), ]
names(df_big5_year_comp)
df_big5_year_comp$yearmon <- as.yearmon(paste(df_big5_year_comp$year,df_big5_year_comp$month), "%y%m")


#--------------------------------------------


gpt(df_big5_year_comp %>% filter(year == 20))+geom_line(aes(x = yearmon, y = `mean(complete)`, color = big_five))
```
#--------------------------------------------
#### 3.5 plots of big5 

```{r}
ggthemr('light',type = 'outer')

comp_big5_plot <- gpt(compar_big5) + aes(x = big5) +
  geom_bar(aes(weights = avg_com, fill = big5)) +
  geom_text(data = compar_big5,
            aes(x = big5,
                y = avg_com %>% round(3),
                label= avg_com),
            size = 9,
            hjust = .7) +
  labs(fill = "Owner Type") +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25))+
  xlab("") +
  ylab("") +
  scale_fill_brewer(palette = "Set3") +
  coord_flip()
comp_big5_plot
#--------------------------------------------


comp_big5_plot3 <- gpt(compar_big5) + aes(x = big5) +
  geom_bar(aes(weights = avg_cap, fill = big5)) +
  geom_text(data = compar_big5,
            aes(x = big5,
                y = avg_cap %>% round(3),
                label= avg_cap),
            size = 9,
            hjust = .7) +
  labs(fill = "Owner Type") +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25))+
  xlab("") +
  ylab("") +
  scale_fill_brewer(palette = "Set3") +
  coord_flip()
comp_big5_plot3

#--------------------------------------------
compar_big5$n2 <- compar_big5$n/sum(compar_big5$n) %>% round(3)
# cumsum(compar_big5$n2) - 0.5*compar_big5$n2

comp_big5_share <-
  gpt(compar_big5) +
  geom_bar(aes(x = "", weight = n2, fill = big5), width = 1, position = "identity") +
  geom_text(aes(x = "", y = cumsum(n2) - 0.5*n2,
                label= n),
            size = 9,
            vjust = 1) +
  coord_polar("y", start=0) +
  theme_void() + 
  # average_completed per month
  labs(fill = "Owner Type",
       title = "Comparation of big-five and non-big-five owned power plant",
       subtitle = "Average Completed per month") +
  scale_fill_brewer(palette = "Set3") +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25),
        legend.position = "none")
comp_big5_share

#--------------------------------------------
#--------------------------------------------

ggsave("../report/comp_big5_share.png", plot = comp_big5_share, width = 12)
ggsave("../report/comp_big5_plot.png", plot = comp_big5_plot, width = 12)
```


```{r}
#--------------------------------------------

  ggsave("../report/comp_big5_plot.png", plot = comp_big5_plot, width = 12)
```


#--------------------------------------------

### 4. causal inference

#--------------------------------------------
```{r}
library(lfe) #felm
```

```{r}
pp_data %>% names

# pp_data_dummy <- fastDummies::dummy_cols(pp_data, select_columns = c("month", "year", "area3"))
# pp_data$yearmonth <- as.yearmon(paste(pp_data$year, pp_data$month), "%y%m")

comp.mean.area3 = (pp_data %>% group_by(yearmonth, area3) %>% summarise(mean(complete)) %>% ungroup())
pp_data_test <- merge(comp.mean.area3, pp_data, by = c("yearmonth", "area3"))
names(pp_data_test)[3] = "mean.com.area3"
#--------------------------------------------
 
pp_data_dummy <- select(pp_data_test, c(-generated_el, -time, -op_time, -area, -plant, -parent_company))

pp_data_dummy$spr_festival <- "0"


pp_data_dummy <- mutate(pp_data_dummy, spr_festival = ifelse(month == 1 & year != 18 | 
                                                               month ==2 & year == 18, "1", "0"))
pp_data <- mutate(pp_data, spr_festival = ifelse(month == 1 & year != 18 | 
                                                               month ==2 & year == 18, "1", "0"))
# pp_data_dummy %>% filter(year == 18) %>% group_by(month) %>% slice(5)

pp_data_dummy <- mutate(pp_data_dummy, bf_covid = ifelse(year != 20 | year == 20 & month == 1, "1", "0"))
pp_data <- mutate(pp_data, bf_covid = ifelse(year != 20 | year == 20 & month == 1, "1", "0"))
#--------------------------------------------
```

#--------------------------------------------
## 4.01 creat comparation data

```{r}
pp_data_dummy <- select(pp_data_dummy, c(-month, -year))
pp_data_dummy %>% names
pp_data_dummy$complete = pp_data_dummy$complete*100
# which(is.na(pp_data_dummy) == T)
# which(pp_data_dummy$area3 == "NA")
# pp_data_dummy <- pp_data_dummy[-which(pp_data_dummy$area3 == "NA"), ]
pp_data_dummy2 <- pp_data_dummy %>% filter(Hydro != 1)
#--------------------------------------------

which(pp_data_dummy2$big_five == 1) %>% length

pp_data_dummy2$complete[which(pp_data_dummy2$big_five == 1)] %>% sum()
# 2664.8/2766
# 0.96341
pp_data_dummy2$complete[which(pp_data_dummy2$big_five != 1)] %>% sum()
# 0.59136
# which(pp_data_dummy2$big_five != 1) %>% length

# exclude hydro
# 5402/9563
# 0.56489
#--------------------------------------------

pp_data_dummy2$capacity[which(pp_data_dummy2$big_five == 1)] %>% sum()
# 82218/2766
# 29.725
pp_data_dummy2$capacity[which(pp_data_dummy2$big_five != 1)] %>% sum()

# 201875/9563
# 21.11

# 189912/9563
# 19.859
#--------------------------------------------

compar_big5 <- data.frame(big5 = c("1","0") %>% as.factor(), 
                          avg_com = c(0.96341, 0.59136), 
                          avg_cap = c(29.725, 21.11), 
                          avg_com.nHydro = c(0.96341, 0.56489), 
                          avg_cap.nHydro = c(29.725,19.859), 
                          n = c(2766, 9563))
#--------------------------------------------


unique((pp_data_dummy2 %>% filter(capacity >= 30))$plant_1) %>% length
unique((pp_data_dummy2 %>% filter(capacity < 30))$plant_1) %>% length
```



```{r}
#--------------------------------------------
str(pp_data_dummy)
# table(pp_data_dummy$big_five)
# pp_data_dummy$big_five <- relevel(pp_data_dummy$big_five, ref = "1")
# DF$b = relevel(DF$b, ref=3)
# two different way to creat naive model.


#--------------------------------------------

# reg1 <- lm(complete ~ spr_festival*big_five + bf_covid*spr_festival+ big_five*bf_covid  +
#              area3
#            , data = pp_data_dummy) # +as.factor(yearmon)
#--------------------------------------------
pp_data$big_five <- as.factor(pp_data$big_five)
pp_data$city <- as.factor(pp_data$city)

pp_data %>% str



names(pp_data_dummy)
reg1 <- felm(complete ~ capacity + big_five + city |yearmonth + area3 , data = pp_data)
# 
reg2 <- felm(complete ~ big_five:bf_covid|yearmonth + plant , data = pp_data)
# coef1 <- summary(reg1)$coef
summary(reg1)$coef
summary(reg2)

mod_stargazer("reg1_naive.text", reg1, type = "text")
```


```{r}
#--------------------------------------------
library(gt)
library(DataExplorer)
# plot_str(pp_data, type = "radial")
# plot_str(iris)
# two different way to creat naive model with interaction terms.

# reg2 <- lm(complete ~ big_five + big_five:spr_festival + big_five:bf_covid + as.factor(yearmonth) + area3, data = pp_data)
# (reg2 %>% summary)$coef %>% data.frame() %>% view
pp_data %>% str
reg_covid <- felm(complete ~ capacity + city + 
                    big_five*capacity + 
                    big_five*spr_festival + big_five*bf_covid + 
                    big_five*bf_covid*type_of_p|area3 + yearmonth, data = pp_data)
            # omit=c("big_five0:spr_festival1","big_five1:bf_covid1"))
#--------------------------------------------
reg_covid %>% stg
mod_stargazer("reg_covid.text", reg_covid, reg1, type = "text", align = T, style = "aer")

```


#### 4.1 monthly fixed effect
```{r}
reg_covid_month <- felm(complete ~ big_five + big_five + 
                    big_five*Hydro + big_five*wind + 
                    big_five*`Fossil.fuel` + big_five*photovoltaic|area3 + yearmonth, data = pp_data)
reg_covid_month %>% stg
```

#--------------------------------------------

### 4.2 covid on different levels/





#--------------------------------------------


### 5. Prediction

```{r}
# library(trelliscopejs)
library(caret)
library(ranger)
library(fastDummies)
library(neuralnet)
library(plm)
library(gbm)
library(gamlr)
library(kernlab)
library(glmnet)
library(e1071)

myControl <- trainControl(
  method = "cv", 
  number = 10,
)
```






```{r}
samplesize = 0.75 * nrow(pp_data_before)
set.seed(123)
index = sample(nrow(pp_data_before), size = samplesize)

# creating training and test set
pp_train = pp_data_before[index,]
pp_test = pp_data_before[-index,]
```

## Linear Regression

```{r message=FALSE, warning=FALSE}
# From previous step
# which(is.na(pp_train))
# names(pp_train)

tuneGrid <- data.frame(
    alpha = seq(0, 1, length = 5),
    lambda = seq(0, 1, length = 20)
)

# Fit random forest: model
lr_model <- train(
  mean.com ~ . ,
  data = pp_train, 
  method = "lm"
  # tuneGrid = tuneGrid,
  # trControl = myControl
)

# Print model to console
# tuneGrid
# lr_model
# plot(lr_model)
```

```{r}
# lr_model$bestTune
# lr_model$finalModel ## dont run
# pp_test <- pp_test %>% filter(pp_test$plant_1 != c("chongfudianchang", "kunpengguangfu", "shangpoguangfu", "wuxiangyongxinguangfu"))
# which(pp_test$plant_1 == "chongfudianchang")

# mod2$xlevels[["y"]] <- union(mod2$xlevels[["y"]], levels(test$y))

pred_mean.com <- predict(lr_model, newdata = pp_test)
pp_test <- cbind(pp_test, pred_mean.com)
```


```{r}

p11 <- ggplot(pp_test, aes(x = pp_test$pred_mean.com, y=pp_test$mean.com)) + 
  geom_point(alpha=0.8, col ="grey") + 
  # scale_x_continuous(limits=c(0,100)) +
  # scale_y_continuous(limits=c(0,100)) +
  geom_abline(intercept=0,slope=1) +
  geom_smooth(se=0,method = "lm") +
  coord_fixed(1) +
  ggtitle("LR")
p11

LR_RMSE <- sqrt(sum((pp_test$pred_mean.com-pp_test$mean.com)^2)/nrow(pp_test))
LR_RMSE
```






```{r}

```

