---
title: "newstuffs"
author: "Siming Yan"
date:   "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: spacelab
    keep_md: true
    toc: yes
    toc_float: true
    highlight: haddock
    
---

<html>
<style> 
div.bgm { background-color:#e6fff0; border-radius: 7px; padding: 10px;} 
.ans {
  color: purple;
  font-weight: bold;
}
#main { 
    color: #2cb061; 
}
</style>

<div class = "bgm">

<ul id="main">

```{r setup, echo=FALSE, cache=FALSE, include = F}


## Global options
options(max.print="75",
        warn =-100)
 
options(digits=5)
options(scipen=5)
# knitr::opts_chunk$set(warning = F, message=F)

```

# read the data

```{r}
pp_new <- read.csv(file = "./rea_pp_data_3.csv")
pp_new %>% names
# pp_new[pp_new$area3 == "luliang",]$area3 = "lvliang"
# which(pp_new$area3 == "luliang")


# pp_new = pp_new[,-c(1, 4,5,6,7, 8)]
```


```{r}
pp_new$efficiency
# pp_new$complete %>% View
pp_new$complete %>% range
pp_new = pp_new[-which(pp_new$complete<0),]


pp_new$efficiency <- pp_new$complete/pp_new$capacity/30/24

# which(is.na(pp_new$efficiency))c
# pp_new[-12585,]
pp_new <- pp_new %>% filter(pp_new$type_of_p != "hydro")
# # pp_new[grep("xingneng", pp_new$plant),]
pp_new <- mutate(pp_new, on_covid = ifelse(bf_covid == "1", "0", "1"))
write.csv(pp_new, "./rea_pp_data_3.csv", fileEncoding = "UTF-8")
#--------------------------------------------

# EFFICEINcy adjustment. 
pp_new$efficiency %>% as.numeric() %>% View

pp_new[12002,] #jianlongdianchang
pp_new[which(pp_new$plant_1 == "jianlongdianchang"),]$capacity = 20

pp_new[8648,] 
pp_new[which(pp_new$plant_1 == "guangyudianchang"),]$capacity = 97
	# guangyudianchang

pp_new[5145,] 
pp_new[which(pp_new$plant_1 == "huilongtaredian"),]$capacity = max(pp_new[which(pp_new$plant_1 == "huilongtaredian"),]$capacity)
# max(pp_new[which(pp_new$plant_1 == "huilongtaredian"),]$capacity)
# 5145
# 1.31786
pp_new[6492,]
pp_new[which(pp_new$plant_1 == "lianchengfengdianchang"),]$capacity = 9.9
# max(pp_new[which(pp_new$plant_1 == "lianchengfengdianchang"),]$capacity)
# 1.30752
# 6701
# 1.11953
# 5229
# 1.06111
#--------------------------------------------

pp_new[2691,]
pp_new[which(pp_new$plant_1 == "sihemeicengqi"),]$capacity = 14
#傻逼行为, 下次别删数据了

# 1.00116
pp_new$efficiency <- pp_new$complete/pp_new$capacity/30/24
```

#--------------------------------------------
# adding econ variables/

```{r}
shanxiGDP <- read_excel("shanxiGDP.xlsx")
names(shanxiGDP)[3] <- "area3"
shanxiGDP
#--------------------------------------------

renkou <- shanxiGDP %>% group_by(year, area3) %>% summarise(GDP/`GDP per capita`)
names(renkou)[3] = "renkou"
shanxiGDP <- merge(shanxiGDP, renkou, by = c("year", "area3"))
# pp_new$generated_el
#--------------------------------------------

pp_new <- merge(shanxiGDP, pp_new, by = c("area3", "year"), all =T)
# # setdiff(pp_new$X, pp_new$X)
# pp_new = pp_new[-which(is.na(pp_new$X)),]
# 
# pp_new$`GDP per capita` = pp_new$`GDP per capita`/10000

pp_new[which(pp_new$year == 20),]$month %>% as.numeric()
```
#--------------------------------------------
# add lags

```{r}
pp_new2 <-  pp_new %>% filter(year != 16) # 后置位数据集
#--------------------------------------------

pp_lag = pp_new
pp_lag %>% filter(year == 16)# 前置位数据

#--------------------------------------------

for (i in 1:dim(pp_lag)[1]){
  if (isTRUE(pp_lag$month[i] != 12) == T){
   pp_lag$month[i] = pp_lag$month[i] + 1 
   # break
  }
  else{
   pp_lag$month[i] = 1 
   # break
  }
  }

for (i in 1:dim(pp_lag)[1]){
  if (isTRUE(pp_lag$month[i] == 1)){
   pp_lag$year[i] = pp_lag$year[i] + 1 
  }
  }
pp_lag 

#--------------------------------------------

pp_lag <- pp_lag %>% filter(year != 20 | (year == 20 & month != 7))

# pp_lag[which(pp_lag$year == 20),] 
pp_lag %>% select(efficiency, plant_1, year, month)

pp_lag_combine <- merge((pp_lag %>% select(efficiency, plant_1, year, month)), pp_new2, 
                        by = c("plant_1", "year", "month"), all = T)
pp_lag_combine %>% names
names(pp_lag_combine)[28] <- "efficiency"



names(pp_lag_combine)[4] <- "efficiency_lag1"
# pp_new[pp_new$X == 386,]
pp_lag_combine$efficiency %>% range


pp_lag_combine <- pp_lag_combine[!is.na(pp_lag_combine$efficiency) == T, ] 
#--------------------------------------------
# pp_lag_combine_test=pp_lag_combine 
# pp_lag_combine 
# pp_lag_combine_test$efficiency = pp_lag_combine_test$efficiency/24/30
```

```{r}
# capacity classification
# pp_lag_combine <- pp_lag_combine %>% mutate(capa_1 = ifelse(capacity < 30, "S",
#                                           ifelse(capacity >= 30 & capacity < 60, "M", "L")))

# pp_lag_combine[which(pp_lag_combine$on_covid == 1),]$month %>% unique # 2-6 month
pp_lag_combine$covid_lag1 = 0
pp_lag_combine[which(pp_lag_combine$on_covid == 1),]$covid_lag1 = 1


pp_lag_combine[pp_lag_combine$year == 20,]
#--------------------------------------------

pp_lag_combine[which(pp_lag_combine$yearmonth == "Jan 2020"),]$covid_lag1 = 0
pp_lag_combine[which(pp_lag_combine$yearmonth == "Jun 2020"),]$covid_lag1 = 1
pp_lag_combine[which(pp_lag_combine$yearmonth == "Jun 2020"),]$on_covid = 0
pp_lag_combine[which(pp_lag_combine$yearmonth == "May 2020"),]$on_covid = 1
pp_lag_combine[which(pp_lag_combine$yearmonth == "Feb 2020"),]$covid_lag1 = 1
# pp_lag_combine[which(pp_lag_combine$on_covid == 1),]$month %>% unique
pp_lag_combine[which(pp_lag_combine$yearmonth == "Jan 2020"),]$on_covid = 1

pp_lag_combine$covid_lag1 = as.factor(pp_lag_combine$covid_lag1)
pp_lag_combine$on_covid = as.factor(pp_lag_combine$on_covid)

#--------------------------------------------

pp_lag_combine[which(pp_lag_combine$covid_lag1 == 1),]$yearmonth %>% unique

pp_lag_combine$month = as.factor(pp_lag_combine$month)
pp_lag_combine$year = as.factor(pp_lag_combine$year)

# dataforsave <- pp_lag_combine
#--------------------------------------------

pp_lag_combine$capacity %>% range
pp_lag_combine$complete %>% range
# which(pp_lag_combine$complete<0)
# pp_lag_combine = pp_lag_combine[-which(pp_lag_combine$complete<0),]
# (pp_lag_combine$complete/pp_lag_combine$capacity) %>% range

pp_lag_combine$year
pp_lag_combine$year = pp_lag_combine$year %>% as.numeric() +16
pp_lag_combine <- merge((pp_lag_combine %>% group_by(yearmonth) %>% summarise(mean(efficiency))), pp_lag_combine, by = "yearmonth", all =T)

pp_lag_combine$year = pp_lag_combine$year %>% as.factor()
p_eff_sum <- gpt(pp_lag_combine) + 
  aes(x = month, y = `mean(efficiency)`, group = year, color = year) + 
  # scale_x_continuous(n.breaks = 12)  + 
  geom_line(size = 1.2L) + 
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25))
p_eff_sum

ggsave(filename = "../report2/p_eff_mean.png", plot = p_eff_sum, width = 12)


pp_lag_combine_test =  pp_lag_combine
# 
# pp_lag_combine
# which(pp_new$year == 16)


```

```{r}
covid <- coronavirus %>%
  filter(country == "China", type == "confirmed")
covid_sx <- covid %>% filter(province == "Shanxi")
covid_sx <- covid_sx %>% mutate(date = ymd(date)) %>% 
  mutate_at(vars(date), funs(year, month, day))
covid_sx_monthly <- covid_sx %>% group_by(month) %>% summarise(sum(cases))
```


```{r}
# ----
# lag case 
# pp_lag_combine$case_lag = 
covid_sx_monthly
covid_sx_monthly$month = covid_sx_monthly$month + 1
covid_sx_monthly$month[6] = 1
names(covid_sx_monthly)[2] = "lag_case"

covid_sx_monthly = covid_sx_monthly[-7,]
covid_sx_monthly$year = "20" %>% as.factor()
pp_lag_combine
merge(covid_sx_monthly, pp_lag_combine, by = c("year", "month"))
pp_lag_combine$month= as.numeric(pp_lag_combine$month)

for (i in 1:6){
  if (pp_lag_combine$month == i & pp_lag_combine$year == 20){
    pp_lag_combine$case_lag = covid_sx_monthly$lag_case[which(covid_sx_monthly$month==i)]
  }
  else {
    pp_lag_combine$case_lag = 0
  }
}


pp_lag_combine[which(pp_lag_combine$yearmonth == "Feb 2020"),]$case_lag = 39
pp_lag_combine[which(pp_lag_combine$yearmonth == "Mar 2020"),]$case_lag = 94
pp_lag_combine[which(pp_lag_combine$yearmonth == "Apr 2020"),]$case_lag = 3
pp_lag_combine[which(pp_lag_combine$yearmonth == "May 2020"),]$case_lag = 61
pp_lag_combine[which(pp_lag_combine$yearmonth == "Jun 2020"),]$case_lag = 1
pp_lag_combine$case_lag %>% unique
write.csv(pp_lag_combine, file = "../report2/pp_lag_combine2.csv")

pp_lag_combine[pp_lag_combine$year == 20, ] %>% View
```

#--------------------------------------------


```{r}
# summary(pp_lag_combine$efficiency)
```


```{r}
# pp_data$bf_covid <- as.factor(pp_data$bf_covid)
# pp_data %>% str
# pp_data_2$type_of_p %>% unique
# pp_data_2 <- within(pp_data_2, type_of_p <- relevel(type_of_p))
# 
# contrasts(pp_data_2$type_of_p) <- contr.treatment(levels(pp_data_2$type_of_p),
   # base=which(levels(pp_data_2$type_of_p) == "fossil-fuel" ))
pp_lag_combine$big_five <- pp_lag_combine$big_five %>% as.factor()

reg_3 <- felm(efficiency ~ 
                    # capacity +
                year +
                new_case +
                big_five +
                on_covid +
                # new_case +
                type_of_p + 
                case_lag+
                covid_lag1+
                # `GDP.per.capita` +

                new_case:type_of_p + 
                new_case:big_five+

                # efficiency_lag1 + 

                on_covid:big_five +
                on_covid:type_of_p+
               covid_lag1:on_covid +
               new_case:case_lag +
                big_five:on_covid:type_of_p|
                month|
                    0 , data = pp_lag_combine)
            # omit=c("big_five0:spr_festival1","big_five1:bf_covid1"))
(summary(reg_3))
# (summary(reg_3)$coef) %>% filter(grep()) %>% View
coeffi3_plot <- summary(reg_3)$coef %>% data.frame()
coeffi3_plot
#--------------------------------------------
coefplot::coefplot(reg_3)
mod_stargazer("../report2/reg_3_1.text", reg_3, type = "text", align = T, style = "aer")
```


# 6. plant name losage

```{r}
setdiff(pp_lag_combine[which(pp_lag_combine$year == 20 & pp_lag_combine$month == 1),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 19 & pp_lag_combine$month == 12),]$plant) #12 
# setdiff(pp_lag_combine[which(pp_lag_combine$year == 19 & pp_lag_combine$month == 12),]$plant, 
        # pp_lag_combine[which(pp_lag_combine$year == 20 & pp_lag_combine$month == 1),]$plant)

setdiff(pp_lag_combine[which(pp_lag_combine$year == 20 & pp_lag_combine$month == 1),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 20 & pp_lag_combine$month == 2),]$plant)   # 21 10   12 2  23 4  34 1 

setdiff(pp_lag_combine[which(pp_lag_combine$year == 20 & pp_lag_combine$month == 3),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 20 & pp_lag_combine$month == 4),]$plant)  # 32  0 #43 4 # 54 2 # 65 3 

# pp_lag_combine$yearmonth[1] %>% mdy() %>% substr(1,7)

# pp_lag_combine[which(pp_lag_combine$year == 19 & pp_lag_combine$month == 12),]$plant

data.frame(monthrange = c("Dec_to_Jan","Jan_to_Feb", "Feb_to_Mar", "Mar_to_Apr", "Apr_to_May"), numbers = c(11, 8, -4, 3))





setdiff(pp_lag_combine[which(pp_lag_combine$year == 20 ),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 19),]$plant) # 27 new in 20

setdiff(pp_lag_combine[which(pp_lag_combine$year == 19 ),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 20),]$plant) # 5 lost

setdiff(pp_lag_combine[which(pp_lag_combine$year == 18 ),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 19),]$plant) # 103 increase
setdiff(pp_lag_combine[which(pp_lag_combine$year == 19 ),]$plant,               # 45 up 18-19
        pp_lag_combine[which(pp_lag_combine$year == 18),]$plant) # 58 lost 


setdiff(pp_lag_combine[which(pp_lag_combine$year == 18 ),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 17),]$plant) # 75+57 lose  132
setdiff(pp_lag_combine[which(pp_lag_combine$year == 17 ),]$plant, 
        pp_lag_combine[which(pp_lag_combine$year == 18),]$plant) # 4 increase 

qp <- data.frame("17-18" = c(132, 4), "18-19" = c(103, 58), "19-20" = c(27,5))
qp[3,] = names(qp)
qp
qp <- qp %>% transpose
qp[4:6, 1:3] = 0
qp$V1[4:6] = qp$V2
qp$V2 =c("increased","increased","increased","decreased" %>% rep(3))
qp$V3[4:6] = qp$V3[1:3]
# qp
qp$V1 = qp$V1 %>% as.numeric()
qpp <- gpt(qp)+
  aes(x = V3, weight = V1, group = V2, fill = V2) + 
  geom_bar(position = "dodge") + 
  geom_text(aes(x = V3, y = V1, group = V2, label = V1),
            position = position_dodge2(width = 1 , preserve = "single"),
            # hjust = 1,
            vjust = .1,
            size = 7) + 
   theme(text = element_text(size =20),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(x = "year change from-to-",
       y = "Number of plants' changes")
qpp 
ggsave("../report/qpp.png", plot = qpp, width = 12)
  # getwd()
```

```{r}
# 市县规划
pp_lag_combine$city = "0"
pp_test$city = "0"

grep("县$", pp_lag_combine$area, value = F) %>% length #8236  #8171
grep("[^县]$", pp_lag_combine$area, value = F) %>% length #2732  4181
# 4181+8171  

#--------------------------------------------
# 末尾切片
str_extract(pp_lag_combine$area, ".$") %>% unique
# "县" "区" "市" "郊" "镇"
# nrow(pp_lag_combine)
index_city1 <- which(str_extract(pp_lag_combine$area, ".$") == "市")
index_city2 <- which(str_extract(pp_lag_combine$area, ".$") == "区")

for (i in 1:12352){
  if (i %in% index_city1){
  pp_lag_combine$city[i] <- "1"
  }
}

for (i in 1:12352){
  if (i %in% index_city2){
  pp_lag_combine$city[i] <- "1"
  }
}

# 8236+ 4093
#--------------------------------------------

pp_lag_combine[grep("[市]$", pp_lag_combine$area, ), ]$area %>% unique 
# which((pp_lag_combine[grep("[市]$",pp_lag_combine$area, ), ]$area %>% length()) == 3)

#--------------------------------------------
 
```

 
```{r}
summary(reg_3)
re3_plot <- ((summary(reg_3))$coef[,] %>% as.data.frame())[18:21,]
re3_plot$rownames = rownames(re3_plot)
re3_plot <- re3_plot %>% separate(rownames, into = c("big5", "on_covid", "type"), sep = "\\:")
rownames(re3_plot)
re3_plot
re3_plotlot <-  gpt(re3_plot) + 
  aes(x = type, y = Estimate, group = type, fill = type) + 
  facet_grid(cols = vars(on_covid),
             scales = "free",
             space = "free")+
   geom_col()  + 
   geom_text(aes(x = type, y = Estimate, label = Estimate %>% round(3)),
            vjust = -0.3) +
  theme(text = element_text(size =20),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Coefficients value of model (3) (part)")

ggsave(filename = "../report2/reg3.png", plot = re3_plotlot, width = 12)
```



```{r}
covid$date %>% max()
asidjij <- covid %>% filter(type == "confirmed") %>% group_by(province) %>% summarise(sum(cases)) 
asidjij[(order(asidjij$`sum(cases)`)),]
```



```{r}
#this is for identifying complete~gdp_per_capita in 16-19
# cgdp$area3
cgdp <- (pp_lag_combine %>% filter(year < 20))
cgdp %>% names()
cgdp$GDP.per.capita

cgdp$efficiency = cgdp$efficiency/30/24
cgdp$GDP.per.capita <- cgdp$GDP.per.capita / 1000
felm(GDP.per.capita ~ complete |yearmon, cgdp) %>% summary
felm(GDP.per.capita ~ efficiency |yearmon, cgdp) %>% summary
```

```{r}
# pp_lag_combine$year
# pp_lag_combine %>% names
pcount
pcount <- pp_lag_combine %>% group_by(yearmonth) %>% summarise(unique(plant_1) %>% length)
pcount$year <- substr(pcount$yearmonth, 4,8) %>% as.numeric()
# pcount$month <- 
pcount$month <- match(substr(pcount$yearmonth, 1,3), month.abb)
pcount <- pcount[order(pcount$year, pcount$month),]



write.csv(pcount, file = "../report2/pcount.csv")
# grep("Sep",pp_data_test$yearmonth , value = T) %>% unique

# which(pp_lag_combine$yearmonth == "Sep 2017")
```

```{r}
# pp_data0 <- read.csv("PP_data.csv")
# pp_data0[which(pp_data0$month == 9), ]$year
# grep("Sep", pp_data0$yearmonth, value = T) %>% unique
```

```{r}
names(pcount)[2] = "num_p"
pcount$year = pcount$year -2000
# pp_lag_combine <- merge(pcount, pp_lag_combine, by = c("yearmonth","year",  "month"))
pp_lag_combine$year %>% unique
pp_lag_combine$year = pp_lag_combine$year %>% as.numeric +16
pp_lag_combine$year <- pp_lag_combine$year %>% as.factor()


unique((pp_data %>% filter(year == 16))$plant) %>% length #211

# dim(pcount)[1]
pcount$new_p = 0

for (i in 2:dim(pcount)[1]){
  pcount$new_p[i] = pcount$num_p[i] - pcount$num_p[i-1]
}

# pcount = pcount[,!names(pcount) %in% c("los_p")]
pcount$new_p[1] = 204-211

pcount 
pp_lag_combine <- merge(pcount, pp_lag_combine_test, by = c("yearmonth","year",  "month"), all = T)
pp_lag_combine$yearmonth %>% unique

# pp_lag_combine[which(pp_lag_combine$yearmonth == "Oct 2017"),]
```

```{r}
# pp_lag_combine[which(pp_lag_combine$year == 18),]$month %>% range

pp_lag_combine <- mutate(pp_lag_combine, spr_festival = ifelse(month == 2 & year == c(18,19) | 
                                                               month == 1 & year == c(17,20), "1", "0"))
pp_lag_combine[pp_lag_combine$spr_festival == 1, ] %>% group_by(year) %>% slice(1)
#--------------------------------------------


write.csv(pp_lag_combine, "../report2/pp_lag_combine_final.csv")
```


```{r}
pp_lag_combine[which(is.na(pp_lag_combine$covid_lag1) == T), ]

pp_lag_combine[pp_lag_combine$covid_lag1 == 1, ] %>% View
#--------------------------------------------
# (((((((((pp_lag_combine$new_p =  pp_lag_combine$new_p/10 )))))))))
#--------------------------------------------

# pp_lag_combine$efficiency <- pp_lag_combine$efficiency/30/24
# pp_lag_combine$efficiency_lag1 <- pp_lag_combine$efficiency_lag1/30/24
pp_lag_combine$efficiency <- pp_lag_combine$efficiency * 100
pp_lag_combine$efficiency_lag1 <- pp_lag_combine$efficiency_lag1*100
# pp_lag_combine[which(pp_lag_combine$on_covid == 1),] 
#--------------------------------------------
# UNIT TRANSFORMATION!!!
# pp_lag_combine$efficiency = pp_lag_combine$efficiency*100
# pp_lag_combine$efficiency_lag1 = pp_lag_combine$efficiency_lag1*100
#--------------------------------------------
 
pp_lag_combine %>% str 
reg1 <- felm(efficiency ~ 
               new_p + 
               on_covid +
               new_case +
               case_lag +
               covid_lag1+
               # covid_lag1:0+
               # spr_festival + 
               # case_lag:new_case+
               covid_lag1:on_covid|
               month|0|plant_1 , 
             data = pp_lag_combine)
(reg1 %>% summary)
# stg(reg1)
library(lmtest)
bptest(reg1)
 #--------------------------------------------


reg2 <- felm(efficiency ~
               new_p +
               on_covid +
               new_case +
               covid_lag1 +
               case_lag+
               type_of_p + # delete this line would cause multi-insignificant. set fossil as baseline.
               on_covid:type_of_p +
               # spr_festival+
               new_case:type_of_p+
               # new_case:case_lag+
               covid_lag1:on_covid|
               month|0|plant_1,
               # year + area3 + plant, 
             data = pp_lag_combine)
# (reg2 %>% stg(omit.stat = "se"))
# (# (reg1 %>% summary)
# getwd()
mod_stargazer("../report2/reg_7.html", reg1, reg2, type = "html", align = T, style = "aer")
mod_stargazer("../report2/reg_2.text", reg2, reg_3, type = "text", align = T, style = "aer")
#--------------------------------------------


tab_model(reg1, reg2,p.style = "stars", show.ci = F, digits = 4)
```



```{r}

reg_3 <- felm(efficiency ~ 
               new_p +
               on_covid +
               new_case +
               covid_lag1 +
               case_lag+
               type_of_p + # delete this line would cause multi-insignificant. set fossil as baseline.
               on_covid:type_of_p +
               # spr_festival+
               new_case:type_of_p+
               # new_case:case_lag+
               covid_lag1:on_covid +
              #--------------------------------------------
              big_five+
               new_case:big_five+
               on_covid:big_five +
               big_five:type_of_p +
              big_five:on_covid:type_of_p|
                month|0|plant_1, data = pp_lag_combine)
            # omit=c("big_five0:spr_festival1","big_five1:bf_covid1"))
stg(reg_3)
# (summary(reg_3)$coef) %>% grep("*")
(summary(reg_3)$coef)
```

```{r}
re3_plot_real <- re3_plot[re3_plot$rownames %in% c("on_covid1", "big_five1:on_covid1", "big_five1:on_covid1:type_of_pphotovoltaic", "big_five1:on_covid1:type_of_pwind","on_covid1:type_of_pphotovoltaic", "on_covid1:type_of_pwind"),]

re3_plot <- (summary(reg_3)$coef) %>% as.data.frame
re3_plot$rownames <- rownames(re3_plot)
# re3_plot <- re3_plot %>% separate(rownames, into = c("big5", "on_covid", "type"), sep = "\\:")
re3_plot_real
#--------------------------------------------
# for non big 5 non covid

nbplot1 <- re3_plot[c("type_of_pphotovoltaic", "type_of_pwind","on_covid1:type_of_pphotovoltaic", "on_covid1:type_of_pwind"), ]
nbplot1[, c(1,5)]

nbplot2 <- (re3_plot[c("type_of_pphotovoltaic", "type_of_pwind","on_covid1:type_of_pphotovoltaic", "on_covid1:type_of_pwind",
           "big_five", "big_five:on_covid1", "big_five:type_of_pphotovoltaic", "big_five:type_of_pwind",
           "big_five:on_covid1:type_of_pphotovoltaic", "big_five:on_covid1:type_of_pwind"), ])[,c(1,5)]

# nbplot2[6:10,][1] -0.44693
```

```{r}
 
re3_plot <- read.xlsx("../report2/effplot.xlsx")
re3_plot$big5 = as.factor(re3_plot$big5)

```




```{r}
 
re3_plotlot <-  gpt(re3_plot) + 
  aes(x = typeofp, y = Estimate, group = typeofp, fill = typeofp) + 
  facet_grid(cols = vars(big5),
             scales = "free",
             space = "free")+
  # facet_grid(cols = vars(big5),
  #            scales = "free",
  #            space = "free")+
   geom_col()  + 
   geom_text(aes(x = typeofp, y = Estimate, label = Estimate %>% round(3)),
            vjust = -0.3) +
  theme(text = element_text(size =20),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 15)) + 
  labs(title  = "Coefficients value of model (3) (part)")
re3_plotlot
ggsave(filename = "../report2/reg3.png", plot = re3_plotlot, width = 12)
```

```{r}
pp_lag_combine$big_five
nb5_comp <- pp_lag_combine%>% group_by(big_five, type_of_p) %>% summarise(mean(efficiency))
nb5_comp 
```

```{r}
ggthemr('light',type = 'outer')
nb5_comp$big_five = as.factor(nb5_comp$big_five)
nb5_comp$`mean(efficiency)` = round(nb5_comp$`mean(efficiency)`,3 )
pnb5_efficience <- ggplot(nb5_comp) +
  geom_col(aes(x = type_of_p, 
                y = `mean(efficiency)`,
                fill = big_five),
            size = 1,
           position = "dodge") +
  # scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Mean Electricity Generating by Type_of_plant",
       x = "Month",
       y = "Mean efficiency generated (10k kwh)")+
  geom_text(aes(x = type_of_p, y = `mean(efficiency)`, label = `mean(efficiency)`, group = big_five),
            position = position_dodge2(width = .82 , preserve = "single"),
            vjust = -.3,
            angle = 0,
            size = 6) +
  scale_fill_brewer(palette = "Set3")
pnb5_efficience 

ggsave(filename = "../report2/effi-type_of_p5.png", plot = pnb5_efficience , width = 12)
```


```{r}
felm(complete ~ 
               # capacity +
               # city +
               
               on_covid +
               new_case+
               type_of_p+# delete this line would cause multi-insignificant. set fossil as baseline.
               on_covid:type_of_p|
               year + month |0|yearmonth + plant_1,
               # year + area3 + plant, 
             data = pp_lag_combine) %>% summary

recom <- felm(complete ~ 
               new_p +
               on_covid +
               new_case +
               covid_lag1 +
               case_lag+
               type_of_p + # delete this line would cause multi-insignificant. set fossil as baseline.
               on_covid:type_of_p +
               # spr_festival+
               new_case:type_of_p+
               # new_case:case_lag+
               covid_lag1:on_covid +
              #--------------------------------------------
              big_five+
               new_case:big_five+
               on_covid:big_five +
               big_five:type_of_p +
              big_five:on_covid:type_of_p|
                month|0|plant_1, data = pp_lag_combine)
recom %>% summary
# mod_stargazer("../report2/reg_11.text", reg_3, recom, type = "text", align = T, style = "aer")
tab_model(reg_3, recom, p.style = "stars", show.ci = F, digits = 4)
```





```{r}
# data stationary test 
options(warn=-1)
library(tseries)

adf.test(pp_lag_combine$efficiency)
## 
##  Augmented Dickey-Fuller Test
## 
## data:  y_stationary
## Dickey-Fuller = -6.8426, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary
adftestd <- pp_new2 %>% group_by(area3, year) %>% summarise(sum(complete))
adftestd[1:4,]$`sum(complete)`
#--------------------------------------------

adf.test(adftestd[1:4,]$`sum(complete)`)

adf.test(pp_new2$GDP)
pp.test(pp_new2$GDP)
pp.test(pp_new2$complete)

which(is.na(pp_new2$GDP))

pp_new2[4849,]

pp_new = read.csv("./rea_pp_data_3.csv")
pp_new[pp_new$area3 == "luliang",]$area3 = "lvliang"
```

# 7. predictions

```{r}
# pppd$area3 %>% unique
pppd <- pp_lag_combine %>% group_by(area3, year) %>% summarise(sum(complete))
pppd[pppd$area3 == "luliang",]$area3 = "lvliang"
pppd <- merge(pppd, shanxiGDP, by =  c("year", "area3"))
pppd <- pppd %>% na.omit()
pppd 

pppd_add <- pp_lag_combine %>% group_by(year, area3) %>% summarise(mean(capacity), mean(efficiency), mean(num_p))
names(pppd_add)[3:5] = c("m_capa", "m_eff", "m_nump")
pppd <- merge(pppd_add,pppd, by = c("year", "area3"))
#--------------------------------------------
# pppd0 = pppd
max = apply(pppd[,c(3:10)], 2, max)
min = apply(pppd[,c(3:10)], 2, min)
scaled = as.data.frame(scale(pppd[,c(3:10)], center = min, scale = max - min))
# scaled
# pppd_save = pppd
pppd = cbind(pppd[ ,-c(3:10)], scaled)
#--------------------------------------------

pppd_bf <- pppd %>% filter(year != 20) %>% na.omit
# pppd_af


pppd_bf
# save_bf_pppd = pppd_bf
#--------------------------------------------

pppd_af <- pppd %>% filter(year == 20) %>% na.omit

# shanxiGDP
# save_bf_pppd
```


```{r}
 # fast dumm
pppd_bf <- fastDummies::dummy_cols(pppd_bf, select_columns = c( "area3" ))
# "month"
pppd_bf <- pppd_bf[,!names(pppd_bf) %in% c(  "area3" )]

# year cannot be a dummy cause u'll have to predict it
#------------------------------------------
pppd_af <- fastDummies::dummy_cols(pppd_af, select_columns = c( "area3" ))
# "month"
pppd_af <- pppd_af[,!names(pppd_af) %in% c(  "area3" )]

# pppd_af  <- pppd_af [,!names(pppd_af ) %in% c("month","year","parent_company", "area", "plant_1" )]
```

```{r}
pppd_bf
names(pppd_bf)[5] = "sum_comp"
samplesize = 0.75 * nrow(pppd_bf)
set.seed(123)
index = sample(nrow(pppd_bf), size = samplesize)
pp_train = pppd_bf[index,]
pp_test = pppd_bf[-index,]


```

```{r}

n <- names(pp_train %>% data.frame)
n
f <- as.formula(paste("GDP ~", paste(n[!n %in% c("GDP", "GDPperMonth", "GDP.per.capita")], collapse = " + ")))
f
#--------------------------------------------
pp_train %>% View()
nn <- neuralnet(f, 
          data = pp_train, 
          hidden = c(21, 8, 8), 
          algorithm = "backprop", 
          linear.output = T, 
          learningrate = 0.0001,
          stepmax=1e+07,
          threshold = .0005)
# 



plot(nn)
```

```{r}
pp_test[,]
predict_testNN = compute(nn, pp_test[,-c(6,7,8)])


predict_testNN = (predict_testNN$net.result * (max(pppd$GDP) - min(pppd$GDP))) + min(pppd$GDP)

pp_test$GDP = (pp_test$GDP * (max(pppd$GDP) - min(pppd$GDP))) + min(pppd$GDP)


#--------------------------------------------
predict_testNN = compute(nn, pppd_af[,-c(6,7,8)])


predict_testNN = (predict_testNN$net.result * (max(pppd$GDP) - min(pppd$GDP))) + min(pppd$GDP)

pppd_af$GDP = (pppd_af$GDP * (max(pppd$GDP) - min(pppd$GDP))) + min(pppd$GDP)
pppd_af$GDPperMonth = (pppd_af$GDPperMonth * (max(pppd$GDPperMonth) - min(pppd$GDPperMonth))) + min(pppd$GDPperMonth)
# pppd_af$`GDP per capita` = (pppd_af$`GDP per capita`  * (max(pppd$`GDP per capita` ) - min(pppd$`GDP per capita` ))) + min(pppd$`GDP per capita` )
```


#--------------------------------------------
# 7.2 gdp loss plot
```{r}
nnplot1 <- ggplot(cbind(pp_test$GDP, predict_testNN) %>% data.frame()) + 
  aes( x = pp_test$GDP, y = predict_testNN) + 
  theme_minimal() +
  geom_point(size =2) + xlim(0,.5) + ylim(0,.5) + 
  geom_abline(slope = 1)  + theme(text = element_text(size = 22),
                                  axis.text = element_text(size = 19),
        plot.title = element_text(size = 25)) 
nnplot1
ggsave("../nnplot1.png", width = 12)

plot(pp_test$GDP, predict_testNN, col='blue', pch=16, ylab = "predicted complete NN", xlab = "real complete"); abline(0,1)

RMSE.NN = (sum((pp_test$GDP - predict_testNN)^2) / nrow(pp_test)) ^ 0.5; RMSE.NN
#--------------------------------------------


predict_testNN/2

pppd_af_new <- cbind(pppd_af, predict_testNN/2) #gdp 是六个月的
pppd_af_new %>% View
pppd_af_new$differ <- pppd_af_new$`predict_testNN/2` - pppd_af_new$GDP

pppd_af_new$differ # total diff, monthly /6
ttloss <- cbind(pppd$area3[1:11], pppd_af_new$differ ) %>% data.frame()
names(ttloss) = c("city name", "GDP loss")

ttloss$`GDP loss` = ttloss$`GDP loss` %>% as.numeric()/6
#--------------------------------------------


#capita 
pppd_af_new
renkou20 <- pppd_af$GDP/ pppd_af$`GDP per capita`
difpercaGDP20 <- pppd_af_new$differ/renkou20

pppd$area3[1:11]
cbind(pppd$area3[1:11],difpercaGDP20 ) %>% data.frame()


pppd$`GDP per capita`
```

```{r}
ttloss$`GDP loss` <- ttloss$`GDP loss` %>% round(3)/1000 %>% round(3)
ttloss$`GDP loss` <- ttloss$`GDP loss`   %>% round(3)
ttloss$`GDP loss` <- ttloss$`GDP loss`/100 #billion
ttloss$`GDP loss` <- ttloss$`GDP loss` %>% round(3)
ttlossplot <- ggplot(ttloss) +
  geom_col(aes(x = `city name`, 
                y = `GDP loss`,
                fill = `city name`),
            size = 1,
           position = "dodge") +
  theme_minimal() +
  # scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 24)) + 
  labs(title  = "",
       x = "Region names",
       y = "GDP per month loss in Billion Yuan")+
  geom_text(aes(x = `city name`, y =  `GDP loss`, label =  `GDP loss`),
            position = position_dodge2(width = .82 , preserve = "single"),
            vjust = -.3,
            angle = 0,
            size = 6) +
  scale_fill_brewer(palette = "Set3")

ggsave("../report2/region_gdploss.png", ttlossplot, width = 12)


```


```{r}
f
myControl <- trainControl(
  method = "cv", 
  number = 10,
)
tuneGrid <- data.frame(
    alpha = seq(0, 1, length = 5),
    lambda = seq(0.0001, 1, length = 20)
)

# Fit random forest: model
lr_model <- train(
  f,
  data = pp_train, 
  method = "glmnet",
  tuneGrid = tuneGrid,
  trControl = myControl
)
# lr_model$bestTune
# lr_model$finalModel ## dont run

# pp_train
# mod2$xlevels[["y"]] <- union(mod2$xlevels[["y"]], levels(test$y))
# 1+1
pred_test_lr <- predict(lr_model, newdata = pp_test)
pp_test_lr <- cbind(pp_test, pred_test_lr)
#--------------------------------------------

# pred_after_lr <- predict(lr_model, newdata = df2)
# pp_after_lr <- cbind(pp_data_after, pred_after_lr)
# # uncenter.
# pp_after_lr$pred_after_lr2 <- (pp_after_lr$pred_after_lr * (max(pp_data_before$complete) - min(pp_data_before$complete))) + min(pp_data_before$complete)

# pp_after_lr %>% group_by(month) %>% summarise(sum(pred_after_lr2))
#--------------------------------------------
```


```{r}

pp_test_lr
plot(pp_test_lr$GDP, pred_test_lr, col='blue', pch=16, ylab = "predicted complete NN", xlab = "real complete"); abline(0,1)

RMSE.NN = (sum((pp_test_lr$GDP - pred_test_lr)^2) / nrow(pp_test_lr)) ^ 0.5; RMSE.NN


lrplot1 <- ggplot(pp_test_lr)  + 
  aes( x =  GDP, y =  pred_test_lr) + 
  theme_minimal() +
  geom_point(size =2) + xlim(0,.5) + ylim(0,.5) + 
  geom_abline(slope = 1)  + theme(text = element_text(size = 22),
                                  axis.text = element_text(size = 19),
        plot.title = element_text(size = 25)) 
lrplot1
ggsave("../lrplot1.png", width = 12)
```




```{r}
set.seed(1)
huatu <- data.frame(a= sample(10) ,
                  out = c(1,3,2,4,5,7,6,8,9,10))
huatu

nn_huatu <- neuralnet(out~a , 
          data = huatu, 
          hidden = c(11, 4, 4), 
          algorithm = "backprop", 
          linear.output = T, 
          learningrate = 0.01,
          stepmax=1e+07,
          threshold = .3)
```


```{r}
library(NeuralNetTools)
plot(nn_huatu)
plotnet(nn_huatu, nid = T, struct = c(0, 21,8,8,1),circle_col = "lightgreen")

#--------------------------------------------

neuralnet::gwplot(nn_huatu)
library(devtools)
source_url("https://gist.githubusercontent.com/Peque/41a9e20d6687f2f3108d/raw/4008477e0aafa05a712d00dc4974011aa10e97a9/nnet_plot_update.r")
library(RSNNS)
# plot.nnet(nn_huatu)

png(filename="../report2/name.png")
plot(nn_huatu)
plotnet(nn_huatu, nid = T, struct = c(0, 21,8,8,1),circle_col = "lightgreen")
dev.print(png, 'filename.png')
dev.off()

sink(file = "../asd.png")
```

# 8. gdp per capita prediction with lr


```{r}
# gdp per capita prediction with lr
f
myControl <- trainControl(
  method = "cv", 
  number = 10,
)
tuneGrid <- data.frame(
    alpha = seq(0, 1, length = 5),
    lambda = seq(0.0001, 1, length = 20)
)
 
lr_model <- train(
  f,
  data = pp_train, 
  method = "glmnet",
  tuneGrid = tuneGrid,
  trControl = myControl
)
 
pred_test_lr <- predict(lr_model, newdata = pp_test)
pp_test_lr <- cbind(pp_test, pred_test_lr)
```

```{r}
#--------------------------------------------
# sort of deviant too much/. forget it !
n <- names(pp_train %>% data.frame)
n
f <- as.formula(paste("GDP.per.capita ~", paste(n[!n %in% c("GDP", "GDPperMonth", "GDP.per.capita")], collapse = " + ")))
f
#--------------------------------------------
pp_train$`GDP per capita`
nn <- neuralnet(`GDP per capita`~ year + m_capa + m_eff + m_nump + sum_comp + 
    renkou + area3_changzhi + area3_datong + area3_jincheng + 
    area3_jinzhong + area3_linfen + area3_lvliang + area3_shuozhou + 
    area3_taiyuan + area3_xinzhou + area3_yangquan + area3_yuncheng, 
          data = pp_train, 
          hidden = c(21, 8, 8), 
          algorithm = "backprop", 
          linear.output = T, 
          learningrate = 0.0001,
          stepmax=1e+07,
          threshold = .001)


predict_testNN = compute(nn, pp_test[,-c(6,7,8)])


predict_testNN = (predict_testNN$net.result * (max(pppd$`GDP per capita`) - min(pppd$`GDP per capita`))) + min(pppd$`GDP per capita`)

pp_test$`GDP per capita` = (pp_test$`GDP per capita` * (max(pppd$`GDP per capita`) - min(pppd$`GDP per capita`))) + min(pppd$`GDP per capita`)

#--------------------------------------------

nnplot2 <- ggplot(cbind(pp_test$`GDP per capita`, predict_testNN) %>% data.frame()) + 
  aes( x = pp_test$`GDP per capita`, y = predict_testNN) + 
  theme_minimal() +
  geom_point(size =2) + xlim(0,.5) + ylim(0,.5) + 
  geom_abline(slope = 1)  + theme(text = element_text(size = 22),
                                  axis.text = element_text(size = 19),
        plot.title = element_text(size = 25)) 
nnplot2
# ggsave("../nnplot1.png", width = 12)

plot(pp_test$`GDP per capita`, predict_testNN, col='blue', pch=16, ylab = "predicted complete NN", xlab = "real complete"); abline(0,1)

RMSE.NN = (sum((pp_test$GDP - predict_testNN)^2) / nrow(pp_test)) ^ 0.5; RMSE.NN
```

