---
title: "PowerPlant-project"
author: "Siming Yan"
date:   "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: spacelab
    keep_md: true
    toc: yes
    toc_float: true
    highlight: haddock
    
---

<html>
<style> 
div.bgm { background-color:#e6fff0; border-radius: 7px; padding: 10px;} 
.ans {
  color: purple;
  font-weight: bold;
}
#main { 
    color: #2cb061; 
}
</style>

<div class = "bgm">

<ul id="main">


```{r setup, echo=FALSE, cache=FALSE, include = F}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               dpi=300,fig.width=7)
opts_knit$set(width=75)
# knitr::opts_chunk$set()
options(digits=5)
options(scipen=5)
knitr::opts_chunk$set(warning = F, message=F)
options(encoding = "UTF-8")
```

### 0. prepare

```{r packages, include = F, warning = F, message = F, }
library(kableExtra)
library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(stargazer)
library(tidyverse)
# library(car)
library(formatR)
# library(plm)
# library(lfe)
library(data.table)
# library(mlogit)
# library(lmtest) #for coeftest() and bptest().
# library(broom) #for glance() and tidy()
# library(RCurl)# For the robust SE method 1
# library(sandwich)
library(texreg) 
library(mice) #check NA
# library(MatchIt)
library(ggthemes)
library(RColorBrewer)
library(readxl)
library(openxlsx)
library(zoo)
```

```{r functions, warning=F, message=F, include = F}
kbt <- function(...){
  knitr::kable(..., format.args = list(big.mark = ',', scientific = F)) %>%
    kableExtra::kable_styling(c("striped", "hover", "condensed"),
                               full_width = F,
                               position = "center",
                               row_label_position = "c") %>%
   row_spec(0, bold = T, color = "white", background = "#004d1f")
}

gpt <- function(...){
  ggplot2::ggplot(...) + 
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
      plot.subtitle = element_text(face = "italic", size = 12, hjust = 0.5), 
      axis.text.x = element_text(angle = 0, hjust = 0.5))
}

stg <- function(...){
  stargazer::stargazer(..., 
          type = "text",
          # style = "qje",
          # title = "daily_kwh ~ post:encouraged|customer_id + no.bill|0|customer_id",
          keep.stat = c("n", "ser"),
          digits = 5)
}
```

```{r 1617data_read}
pp_list <- list.files(path = "../16_17/") 
pp_list <- pp_list[1:12]

xlist <- paste("../16_17/", list.files("../16_17"), sep = "")
xlist <- xlist[1:12]

#--------------------------------------------
```


```{r 2016sample}
data16 <- read_xls(xlist[1], skip = 3,  col_names = TRUE)  # read_data.

colnames(data16) <- c("num", "plant", "capacity", "designed_capacity", "complete", "generated_el", "time", "month", "year") # rename data.
 

data_16 <- data16[,-1] # delete first col 
data_16 <- data_16[-{1:8},] # delete first eight row which are sum-up data

data_16 <- data_16[!grepl("^?\\d", data_16$plant),] # delete all number start rows. (those are integrated company data)
data_16 <- data_16[!grepl("^\\w", data_16$plant),] # delete which has letters as serial number.

write.csv(data_16, file = "./data/data_16.csv")

remove(data16, data_16)
```


```{r data16#1617年的数据, message = F, error = F}

All <- lapply(xlist, function(filename){
    # print(paste("Merging", filename, sep = " "))
    read_xls(filename, skip = 12, col_names = F)
})

df <- do.call(rbind.data.frame, All)
# write.xlsx(df, "./data/data_merge.xlsx")

colnames(df) <- c("num", "plant", "capacity", "designed_capacity", "complete", "generated_el", "time", "month", "year") # rename data.
 
df <- df[!grepl("^\\d{1,2}[[:punct:]]", df$plant), ] # delete all number start rows. (those are integrated company data)
df <- df[!grepl("^\\w{1}[[:punct:]]", df$plant), ] # delete which has letters as serial number.
df <- df[!grepl("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]{1,3}[.、]", df$plant), ]


df <- df[!is.na(df$plant),]

df_2017 <- df
```


```{r 1819year#读取}
pp_list_2 <- list.files(path = "../18/")
xlist_2 <- paste("../18/", list.files("../18"), sep = "")
```


```{r 1819year#数据清洗, warning = F, message = F}
All2 <- lapply(xlist_2, function(filename){
  read_xls(filename, skip = 12, col_names = F)
})

#--------------------------------------------读取
for (f in 1:24) {
  All2[[f]]$monthyear <- pp_list_2[f]
}
#--------------------------------------------添加时间
drop_li <- c("...7")
All2[[17]] <- All2[[17]][ , !(names(All2[[17]]) %in% drop_li)]
drop_li <- c("...8","...9","...10")
All2[[22]] <- All2[[22]][ , !(names(All2[[22]]) %in% drop_li)]

for (f in 1:24){
  names(All2[[f]]) <- c(1:8)
}


```


```{r 1819year#数据清洗2}
df <- do.call(rbind.data.frame, All2)

colnames(df) <- c("num", "plant", "capacity", "designed_capacity", "complete", "generated_el", "time", "yearmonth")

df <- df[!grepl("^\\d{1,2}[[:punct:]]", df$plant), ] # delete all number start rows. (those are integrated company data) #1. 
df <- df[!grepl("^[[:alpha:]][[:punct:]]", df$plant), ] # delete which has letters as serial number.
df <- df[!grepl("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]{1,3}[.、]", df$plant), ]


df_1819 <- df[, -1]
```

```{r 1819year#数据清洗3}
df_1819 <- mutate(df_1819, yearmonth = 
                    gsub("[[:punct:]]xls", "", df_1819$yearmonth)) 

df_1819 <- df_1819 %>%
  mutate(month = gsub("\\d{2}[[:punct:]]",
                      "",
                      df_1819$yearmonth)) 

df_1819$month <- df_1819$month %>% as.numeric() 

#--------------------------------------------# month
df_1819 <- mutate(df_1819, 
                 year = ifelse(grepl("19", df_1819$yearmonth)==T, 
                               19, 18))
#--------------------------------------------# year

df_1819 <- df_1819[, -7]
```

```{r combination#合并}
df <- rbind(df_2017, df_1819)
df <- df[!grepl("乐平", df$plant),] # delete 乐平电厂，messed up

df$time <- df$time %>% as.numeric() %>% round(3)
df$generated_el <- df$generated_el %>% as.numeric() %>% round(3)
df$complete <- df$complete %>% as.numeric() %>% round(3)
```

```{r}
df_name <- data.frame(unique(df$plant))
write.csv(df_name, "./df_name.csv", fileEncoding = "UTF-8")
```


$$
\begin{eqnarray*}\\
23\\
23\\
32\\
33

\tag{1-b.}
\end{eqnarray*}
$$
```{r 1819year}

df_1819 <- mutate(df_1819, 
                 year = ifelse(grepl("19", df_1819$yearmon)==T, 
                               19, 18))

grep("^\\d{1,2}[[:punct:]]", df$plant, value = T)
grep("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]{1,3}[.、]", df$plant, value = T)
```


```{r TestForRe正则表达式1}
USArrests %>% head()

states <- data.frame(USArrests, check.names = T, row.names = c(1:50)) %>% 
  cbind(state = row.names(USArrests))

states[3, 5] <- "1. Arizona"
# grep(pattern = "w", x = states, value = TRUE)
states2 <- states[!grepl("\\d", states$state),]
colnames(states2) <- c("num", "plant", "capacity", "designed_capacity", "complete")
```


```{r tst_lines}

test <- df[1:20,]
test[3, 2] <- "Dongshan#1"
test[4, 2] <- "D. digshan#2"
test[5, 2] <- "五台山shan#2"
test[6, 2] <- "三、digshan#2"
test[7, 2] <- "三.digshan#2"
# test <- test[!grepl("^?\\d", test$plant), ] # delete all number start rows. (those are integrated company data)
# test2 <- test[!grepl("^?\\w", test$plant), ]
# test3 <- test[!grepl("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]", test$plant), ]
#--------------------------------------------
## test <- df[212:214,]
## test <- mutate(test, ifelse(plant == grep("一")))

# ch_list <- c("一", "二", "三", "四", "五", "六", "七", "八", "九", "十")
# test[!grepl("[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]、", test$plant), ]
test <- test[!grepl("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十][.、]", test$plant), ]
#--------------------------------------------
#--------------------------------------------


```





<!-- #-------------------------------------------- -->
### following part contains read all exl documents in assigned dataframes.

```{r load_data, include = F}
pp_list <- list.files(path = "../16_17/") 
xlist <- paste("../16_17/", list.files("../16_17"), sep = "")
for(f in 1:length(pp_list)) {
  # file_name <- str_sub(string = pp_list[f])
  file_name <- pp_list[f]
  file_df <- read_xls(xlist[f], skip = 3)  
  file_df <- file_df[,2:7] #if you only need the first three columns
  assign(x = file_name, value = file_df, envir = .GlobalEnv)
}
```

```{r, message = F, warning = F}
pp_list <- list.files(path = "../18/") 
xlist <- paste("../18/", list.files("../18/"), sep = "")
for(f in 1:length(pp_list)) {
  # file_name <- str_sub(string = pp_list[f])
  file_name <- pp_list[f]
  file_df <- read_xls(xlist[f], skip = 2, col_names = F)  
  file_df <- file_df[ , 1:7] #if you only need the first three columns
  file_df$monthyear <- pp_list[f]
  assign(x = file_name, value = file_df, envir = .GlobalEnv)

}
```
