---
title: "PowerPlant-project"
author: "Siming Yan"
date:   "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    theme: spacelab
    keep_md: true
    toc: yes
    toc_float: true
    highlight: haddock
    
---

<html>
<style> 
div.bgm { background-color:#e6fff0; border-radius: 7px; padding: 10px;} 
.ans {
  color: purple;
  font-weight: bold;
}
#main { 
    color: #2cb061; 
}
</style>

<div class = "bgm">

<ul id="main">


```{r setup, echo=FALSE, cache=FALSE, include = F}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               dpi=300,fig.width=7)
opts_knit$set(width=75)
# knitr::opts_chunk$set()
options(digits=5)
options(scipen=5)
knitr::opts_chunk$set(warning = F, message=F)

```

### 0. prepare

```{r packages, include = F, warning = F, message = F, }
library(kableExtra)
library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(stargazer)
library(tidyverse)
# library(car)
library(formatR)
# library(plm)
# library(lfe)
library(data.table)
# library(mlogit)
# library(lmtest) #for coeftest() and bptest().
# library(broom) #for glance() and tidy()
# library(RCurl)# For the robust SE method 1
# library(sandwich)
library(texreg) 
library(mice) #check NA
# library(MatchIt)
library(ggthemes)
library(RColorBrewer)
library(readxl)
library(openxlsx)
library(zoo)


ggthemr('light',type = 'outer')
```

```{r functions, warning=F, message=F, include = F}
kbt <- function(...){
  knitr::kable(..., format.args = list(big.mark = ',', scientific = F)) %>%
    kableExtra::kable_styling(c("striped", "hover", "condensed"),
                               full_width = F,
                               position = "center",
                               row_label_position = "c") %>%
   row_spec(0, bold = T, color = "white", background = "#004d1f")
}

gpt <- function(...){
  ggplot2::ggplot(...) + 
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
      plot.subtitle = element_text(face = "italic", size = 12, hjust = 0.5), 
      axis.text.x = element_text(angle = 0, hjust = 0.5))
}

stg <- function(...){
  stargazer::stargazer(..., 
          type = "text",
          # style = "qje",
          # title = "daily_kwh ~ post:encouraged|customer_id + no.bill|0|customer_id",
          keep.stat = c("n", "ser"),
          digits = 5)
}
```

---

#--------------------------------------------
## 1. data 1617

```{r 1617data_read}
pp_list <- list.files(path = "../16_17/") 
pp_list <- pp_list[1:12]

xlist <- paste("../16_17/", list.files("../16_17"), sep = "")
xlist <- xlist[1:12]

#--------------------------------------------
```

```{r data16#1617年的数据, message = F, error = F}
All <- lapply(xlist, function(filename){
    # print(paste("Merging", filename, sep = " "))
    read_xls(filename, skip = 12, col_names = F)
})
df <- do.call(rbind.data.frame, All)

colnames(df) <- c("num", "plant", "capacity", "designed_capacity", "complete", "generated_el", "time", "month", "year", "parent_company") # rename data.
 
df <- df[!grepl("^\\d{1,2}[[:punct:]]", df$plant), ] 
 # delete all number start rows. (those are integrated company data)
df <- df[!grepl("^\\w{1}[[:punct:]]", df$plant), ] 
 # delete which has letters as serial number.

df <- df[!grepl("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]{1,3}[.、]", df$plant), ]

df <- df[!is.na(df$plant),]

df_2017 <- df[,-1]


df_2017 <- df_2017[!grepl("回龙塔", df$plant), ] # wrong data
df_2017 <- mutate(df_2017, year = 
                    gsub("^\\d{2}", "", df_2017$year)) 
remove(df)

#--------------------------------------------

# sum((df_2017 %>% filter(year == 16))$complete)
# 186.83
```
 
 
 
 
```{r data1_pa, message = F, error = F, eval = F, include = F}

#adding parent company 1
#-------------------------------------------- 7.15 ,parent name change.

df_2017$parent_company <- gsub("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]{1,3}[.、]", "",  #1-3digit number, either . or \ !match
                               df_2017$parent_company)

df_2017$parent_company <- gsub("^\\w{1,3}[.、]", "", 
                               df_2017$parent_company)


#--------------------------------------------

# which(is.na(df_2017$parent_company))
df_2017$parent_company[2670] = "else"
 

df_2017 %>% group_by(parent_company) %>% summarise(n())

# which(df_2017$parent_company == "山西煤电一体化")
# df_2017[1541,]
#--------------------------------------------#delete 110kv etc name prefix
# grep("^\\d{1,3}[kV, kv, KV, Kv]", df_2017$plant)
# df_2017$plant <- gsub("^\\d{1,3}[kK][vV]", "", 
                               # df_2017$plant)

df_2017 <- df_2017[!is.na(df_2017$capacity), ]
```

```{r ap2}
appendix2 <- read_excel("./data/appendix2.xlsx")
appendix2 <- appendix2[,-c(2,4,6)]
colnames(appendix2) <- c("plant",  "parent_company", "op_time")

#--------------------------------------------# delete 110kv etc name prefix
appendix2$plant <- gsub("^\\d{1,3}[kK][vV]", "",
                               appendix2$plant)


```

```{r alternatv_parent}
df_2017_2 <- df_2017[,-9]
df_2017_2 <- merge(df_2017_2, appendix2, by = "plant", all = T, incomparables = T, no.dups = T)

df_2017_2 <- df_2017_2[!is.na(df_2017_2$capacity), ]

df_2017_2$parent_company <- replace_na(df_2017_2$parent_company, "else")
```



#--------------------------------------------
## 2. data 181920

```{r 1819year#读取}
pp_list_2 <- list.files(path = "../18_19/")
xlist_2 <- paste("../18_19/", list.files("../18_19"), sep = "")
```


```{r 1819year#数据清洗, warning = F, message = F}
All2 <- lapply(xlist_2, function(filename){
  read_xls(filename, skip = 12, col_names = F)
})

#--------------------------------------------读取
for (f in 1:30) {
  All2[[f]]$monthyear <- pp_list_2[f]
}
#--------------------------------------------添加时间
drop_li <- c("...7")
All2[[17]] <- All2[[17]][ , !(names(All2[[17]]) %in% drop_li)]
drop_li <- c("...8","...9","...10")
All2[[22]] <- All2[[22]][ , !(names(All2[[22]]) %in% drop_li)]

for (f in 1:30){
  names(All2[[f]]) <- c(1:8)
}


```


```{r 1819year#数据清洗2, warning = F}

df <- do.call(rbind.data.frame, All2)

colnames(df) <- c("num", "plant", "capacity", "designed_capacity", "complete", "generated_el", "time", "yearmonth")

df <- df[!grepl("^\\d{1,2}[[:punct:]]", df$plant), ] # delete all number start rows. (those are integrated company data) #1. 
df <- df[!grepl("^[[:alpha:]][[:punct:]]", df$plant), ] # delete which has letters as serial number.
df <- df[!grepl("^[一, 二, 三, 四, 五, 六, 七, 八, 九, 十]{1,3}[.、]", df$plant), ]


df_1819 <- df[, -1]

```

```{r 1819year#数据清洗3}

df_1819 <- mutate(df_1819, yearmonth = 
                    gsub("[[:punct:]]xls", "", df_1819$yearmonth)) 

df_1819 <- df_1819 %>%
  mutate(month = gsub("\\d{2}[[:punct:]]",
                      "",
                      df_1819$yearmonth)) 

df_1819$month <- df_1819$month %>% as.numeric() 



#--------------------------------------------# month
 

df_1819 <- mutate(df_1819, 
                 year = gsub("[[:punct:]]\\d{1,2}", "", df_1819$yearmonth))
                    

# df_1819 %>% head
#--------------------------------------------# year

df_1819 <- df_1819[, -7]
```


#--------------------------------------------
##2.1 parent company

```{r}
# grep("^\\d{2,3}[kK][Vv]", df_1819$plant)
df_1819$plant <- gsub("^\\d{1,3}[kK][vV]", "",
                               df_1819$plant)


df_1819 <- merge(df_1819, appendix2, by = "plant", all = T, incomparables = T, no.dups = T)

df_1819 <- df_1819[!is.na(df_1819$capacity), ]

df_1819$parent_company <- replace_na(df_1819$parent_company, "else")

```




#--------------------------------------------

## 3. data 16-19 comb
```{r combination#合并}
df <- rbind(df_2017_2, df_1819)
df <- df[!grepl("乐平", df$plant),] # delete 乐平电厂，messed up

df$time <- df$time %>% as.numeric() %>% round(3)
df$generated_el <- df$generated_el %>% as.numeric() %>% round(3)
df$complete <- df$complete %>% as.numeric() %>% round(3)


#--------------------------------------------


df$parent_company[df$parent_company == "其他"] = "else"
df$parent_company[df$parent_company == "其它电厂"] = "else"
df$parent_company[df$parent_company == "其它"] = "else"
```


```{r write#存储}
# df <- df[order(df$plant), ]
df$plant <- gsub("光伏电站", "光伏", df$plant)
 # substring(pp_data$area, 1, 2) %>% unique
df$plant <- gsub("忻州|晋城|运城|大同|太原|阳泉|晋中|临汾|朔州|长治|吕梁","", df$plant)
df <- df[order(df$plant), ]

df$plant <- gsub("右玉圣水塘", "圣水塘风电场", df$plant)
# df[grep("光伏电", df$plant), ]


df <- df[order(df$plant), ]
#--------------------------------------------
for (t in 1:40){
  for (i in 1:12396){
    if(df$parent_company[i] == "else"){
      if(isTRUE((df$plant[i] == df$plant[i+1]) == T)){
        if(isTRUE((df$parent_company[i+1] != "else") == T)){
          df$parent_company[i] = df$parent_company[i+1]
      }
    }
  }
  }
  t = t+1
}

for (t in 1:40){
  for (i in 1:12396){
    if(df$parent_company[i] == "else"){
      if(isTRUE((df$plant[i] == df$plant[i-1]) == T)){
        if(isTRUE((df$parent_company[i-1] != "else") == T)){
          df$parent_company[i] = df$parent_company[i-1]
      }
    }
  }
  }
  t = t+1
}

#--------------------------------------------
# df_water <- df[grep("[水]", df$plant), ]

# df$plant[2] == df$plant[2+1]
```


```{r write#存储2}
write.csv(df, file = "./data/PP_data.csv")
```

<!-- #-------------------------------------------- -->
#--------------------------------------------
#--------------------------------------------
#--------------------------------------------

```{r reread}
df <- read.csv("./data/PP_data.csv")
```
<!-- #-------------------------------------------- -->

#--------------------------------------------
## 4. Plots of first pre
#### including : data description part

#--------------------------------------------

```{r, warning = F}
df <- df[!is.na(df$complete), ]
dfp <- df %>% group_by(month, year) %>% summarise(sum(complete))
dfp <- filter(dfp, year != 16)
dfp$year <- as.factor(dfp$year)
```


```{r}

ggthemr('light',type = 'outer')
p  <- ggplot(dfp) +
  geom_line(aes(x = month, 
                y = `sum(complete)`, 
                group = year,
                color = year),
            size = 1.2) +
   geom_point(aes(x = month, 
                y = `sum(complete)`, 
                group = year,
                color = year),
              color = "black",
              alpha = I(1/3),
              shape = 17,
            size = 1.8) +
  scale_x_continuous(n.breaks = 12)  +
  theme(text = element_text(size =16),
        plot.title = element_text(size = 25)) + 
  labs(title  = "Power-plant electricity generated",
       x = "month",
       y = "sum energy generated per month")
p


# ggsave(filename = "./el-gen.png", plot = p, width = 12)

# gg theme assist
```

```{r}
pp_data <- read.csv("./data/pp_data_real.csv")

pp_data$yearmonth <- as.yearmon(paste(pp_data$year, pp_data$month), "%y%m")
pp_data_20 <- filter(pp_data, year == c(20))



pp_area_p <- pp_data_20 %>% group_by(area3, month) %>% summarise(sum(complete)) %>% ungroup

pp_area_p <- pp_area_p %>% na.omit()
  

  

install.packages("viridis")  # Install
library("viridis") 


p  <- ggplot(pp_area_p) +
  geom_line(aes(x = month, 
                y = `sum(complete)`, 
                group = c(area3),
                color = c(area3)),
            size = 1) +
  scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size = 21),
        plot.title = element_text(size = 29),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Electricity generated by city in 2020",
       x = "Month",
       y = "Sum energy generated per month")+
  facet_grid(cols = vars(area3))+
  # scale_color_wsj(palette = "rgby")
  scale_color_manual(values = c("#7e3eed","#aa6cf1","#bbd8f9","#dd3315","orchid1",
                                "#dd6c58","#e69b80","#f4c1e5","#12d436","#12d9e3",
                                "#7d9843","#8bb557","#e9c07a","#3e257c","#8e0f83"))
p



ggsave(filename = "./el-gen-city.png", plot = p, width = 19)

  # scale_color_brewer(palette = "Set3")

  # set_swatch(c("#1ecbe1", "red"))
# p <- {}
# pp_area_p %>% head
# 
# for (i in 1:11){
#   p[i] <- paste0("p", i)
#   p[i][[1]] <- ((filter(pp_area_p ,area3 == (pp_area_p$area3 %>% unique)[i]) %>% 
#   ggplot() + aes(x = yearmonth, y = `sum(complete)`, color = area3) +
#     geom_line()) +
#     scale_x_yearmon(breaks = pp_area_p$yearmonth) +
#     theme(axis.text.x = element_text(angle = 25)))
#  
# }
# 
# p2
# 
# 
# p <- {}
# 
# for (i in 1:11){
#   p[i] <- paste0("p", i)
# }

# ggplot
```

```{r}
pp_area_p2 <- pp_data_20 %>% group_by(big_five, month) %>% summarise(sum(complete)) %>% ungroup

pp_area_p2 <- pp_area_p2 %>% na.omit()

pp_area_p2$big_five <- as.factor(pp_area_p2$big_five)

  
p2  <- ggplot(pp_area_p2) +
  geom_line(aes(x = month, 
                y = `sum(complete)`,
                color = big_five),
            size = 1) +
  scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size =16),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Electricity generated by OwnerType in 2020",
       x = "Month",
       y = "Sum energy generated per month")+
  facet_grid(cols = vars(big_five))+
  scale_color_brewer(palette = "Set1")
p2

ggsave(filename = "./el-gen-owntype.png", plot = p2, width = 12)

```

```{r}
pp_data_20 <- mutate(pp_data_20, type_of_p = 
                       ifelse(wind == "1", "wind", 
                              ifelse(Hydro == "1", "hydro", 
                                     ifelse(Fossil.fuel == "1", "fossil-fuel", "photovoltaic")
)))


pp_area_p3 <- pp_data_20 %>% group_by(type_of_p, month) %>% summarise(sum(complete)) %>% ungroup

pp_area_p3 <- pp_area_p3 %>% na.omit()



  
p3  <- ggplot(pp_area_p3) +
  geom_line(aes(x = month, 
                y = `sum(complete)`,
                color = type_of_p),
            size = 1) +
  scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size =16),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Electricity generated by Type_of_plant in 2020",
       x = "Month",
       y = "Sum energy generated per month")+
  facet_grid(cols = vars(type_of_p),
             scales = "free",
             space = "free")+
  scale_color_brewer(palette = "Set1")
p3

ggsave(filename = "./el-gen-type_of_p.png", plot = p3, width = 12)


pp_area_p4 <-  pp_area_p3 %>% filter(type_of_p != "fossil-fuel")

p4 <- ggplot(pp_area_p4) +
  geom_line(aes(x = month, 
                y = `sum(complete)`,
                color = type_of_p),
            size = 1) +
  scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size =16),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Electricity generated by Type_of_plant in 2020",
       x = "Month",
       y = "Sum energy generated per month")+
  facet_grid(cols = vars(type_of_p),
             scales = "free",
             space = "free")+
  scale_color_brewer(palette = "Set1")
p4
ggsave(filename = "./el-gen-type_of_p2.png", plot = p4, width = 12)

```

#--------------------------------------------



```{r}
pp_data <- mutate(pp_data, type_of_p = 
                       ifelse(wind == "1", "wind", 
                              ifelse(Hydro == "1", "hydro", 
                                     ifelse(Fossil.fuel == "1", "fossil-fuel", "photovoltaic")
)))



pp_area_p5 <-  pp_data %>% group_by(big_five, type_of_p) %>% summarise(mean(capacity), mean(complete))

# unique((pp_data %>% filter(Hydro == 1))$plant)
# pp_data %>% filter(Hydro == 1)
pp_area_p5

```


```{r}
pp_area_p5$big_five <- pp_area_p5$big_five %>% as.factor()
pp_area_p5$`mean(complete)` <- pp_area_p5$`mean(complete)` %>% round(3)
pp_area_p5$`mean(capacity)` <- pp_area_p5$`mean(capacity)` %>% round(3)

p5 <- ggplot(pp_area_p5) +
  geom_col(aes(x = type_of_p, 
                y = `mean(complete)`,
                fill = big_five),
            size = 1,
           position = "dodge") +
  # scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size =16),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Mean Electricity Generating by Type_of_plant",
       x = "Month",
       y = "Mean electricity generated (Gwh)")+
  geom_text(aes(x = type_of_p, y = `mean(complete)`, label = `mean(complete)`, group = big_five),
            position = position_dodge2(width = .82 , preserve = "single"),
            vjust = -1,
            angle = 0,
            size = 4.5) +
  scale_color_brewer(palette = "Set1")
p5

#--------------------------------------------
p6 <- ggplot(pp_area_p5) +
  geom_col(aes(x = type_of_p, 
                y = `mean(capacity)`,
                fill = big_five),
            size = 1,
           position = "dodge") +
  # scale_x_continuous(n.breaks = 6)  +
  theme(text = element_text(size =16),
        plot.title = element_text(size = 25),
        axis.text.x = element_text(angle = 0)) + 
  labs(title  = "Mean Capacity by Type_of_plant",
       x = "Type of Plant",
       y = "Mean Capacity (10k.kw)")+
  geom_text(aes(x = type_of_p, y = `mean(capacity)`, label = `mean(capacity)`, group = big_five),
            position = position_dodge2(width = .82 , preserve = "single"),
            vjust = -1,
            angle = 0,
            size = 4.5) +
  scale_color_brewer(palette = "Set1")
p6

ggsave(filename = "./el-gen-type_of_p3.png", plot = p5, width = 12)
ggsave(filename = "./el-gen-type_of_p4.png", plot = p6, width = 12)

```