---
title: "print making graphs 1"
author: "Siming Yan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
    html_document:
      theme: spacelab
      keep_md: true
      highlight: haddock

---

```{r setup, echo=FALSE, cache=FALSE, include = F}
library(knitr)
## Global options
options(max.print="75")
knitr::opts_chunk$set(
	fig.width = 7,
	message = FALSE,
	warning = FALSE,
	# cache = TRUE,
	# comment = NA,
	dpi = 300,
	# prompt = FALSE,
	tidy = TRUE,
	qwraps2_markup = "markdown",
	comment=NA, prompt=FALSE, cache=TRUE, echo=TRUE, results='asis'
)
opts_knit$set(width=75)
options(digits=5)
options(scipen=5)


# st_options(bootstrap.css     = FALSE,       # Already part of the theme so no need for it
#            plain.ascii       = FALSE,       # One of the essential settings
#            style             = "rmarkdown", # Idem.
#            dfSummary.silent  = TRUE,        # Suppresses messages about temporary files
#            footnote          = NA,          # Keeping the results minimalistic
#            subtitle.emphasis = FALSE)       # For the vignette theme, this gives better results.
#                                             # For other themes, using TRUE might be preferable.
```

### set
 
```{r setup2, include=FALSE}

library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(scales)
library(stargazer)
library(tidyverse)
# library(car)
library(formatR)
# library(plm)
# library(lfe)
library(data.table)
# library(mlogit)
# library(lmtest) #for coeftest() and bptest().
# library(broom) #for glance() and tidy()
# library(RCurl)# For the robust SE method 1
# library(sandwich)
library(texreg) 
library(mice) #check NA
# library(MatchIt)
library(ggthemes)
library(RColorBrewer)
library(readxl)
library(openxlsx)
library(zoo)
library(pinyin)
library(ggthemr)
library(kableExtra)
library(plotly)

library(summarytools)
```

```{r functions, warning=F, message=F, include = F}
kbt <- function(...){
  knitr::kable(..., format.args = list(big.mark = ',', scientific = F)) %>%
    kableExtra::kable_styling(c("striped", "condensed"),
                               full_width = F,
                               position = "center",
                               row_label_position = "c") %>%
   row_spec(0, bold = T )
}

gpt <- function(...){
  ggplot2::ggplot(...) + 
    theme_minimal() +
    theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
      plot.subtitle = element_text(face = "italic", size = 12, hjust = 0.5), 
      axis.text.x = element_text(angle = 0, hjust = 0.5))
}

stg <- function(...){
  stargazer::stargazer(..., 
          type = "text",
          # style = "qje",
          # title = "daily_kwh ~ post:encouraged|customer_id + no.bill|0|customer_id",
          keep.stat = c("n", "ser"),
          digits = 5)
}

gpt_area <- function(in_data, in_x, in_y, in_times, heading, heading_x,heading_y){
  gpt(in_data) +
  # geom_point(aes(x = in_x, 
  #              y = in_times*in_y), 
  #          alpha = I(.8)) +
  # geom_line(aes(x = in_x, 
  #              y = in_times*in_y,
  #              group = 1)) +
  geom_bar(aes(x = in_x, 
               weight = in_y,
               alpha = I(.9))) +
  theme(axis.text.x = element_text(angle = 0, hjust = .6)) +
  geom_text(data = in_data,
            aes(x = in_x,
                y = in_y,
                label= in_y),
            size = 5, 
            vjust = -0.2) +
  labs(title  = heading,
       x = heading_x,
       y = heading_y) +
  theme(text = element_text(size = 22),
        plot.title = element_text(size = 25))
}

mod_stargazer <- function(output.file, ...) {
  output <- capture.output(stargazer(...))
  cat(paste(output, collapse = "\n"), "\n", file=output.file, append=F)
}

ggthemr('light',type = 'outer')

```

```{r, include=F}
pp_data <- read.csv("./pp_data_real.csv")
```

#--------------------------------------------
## 1. summary data

```{r, echo = F, eval=FALSE}
# percent(9563 / (9563 + 2766))
pp_data$Fossil.fuel <- as.numeric(pp_data$Fossil.fuel)
pp_data$big_five <- as.numeric(pp_data$big_five)
# pp_summary <- (pp_data %>% data.frame() %>% summary) %>% data.frame()
# # pp_summary$Var2[22]
# pp_summary %>% filter(Var2 == "   complete")


library(qwraps2)
# options(qwraps2_markup = "markdown")
#--------------------------------------------

# type_of_p
our_summary1 <-
  list("Plant" =
       list("Unique Names of Plants" = ~ length(unique(plant))),
      "Electricity generated per month" =
       list("Electricity generated per month" = ~ print(""),
            "min"       = ~ min(complete),
            "median"    = ~ median(complete),
            "max"       = ~ max(complete),
            "mean (sd)" = ~ qwraps2::mean_sd(complete))
  )

# length(pp_data$plant %>% unique)
# pp_data %>% group_by(type_of_p) %>% (max(yearmon) %>% as.Date() - min(yearmon) %>% as.Date())

# unique(paste0(pp_data$big_five, pp_data$plant)) %>% length

st1 <- summary_table(group_by(pp_data, type_of_p), our_summary1) %>% kbt %>%
  add_header_above(header = c("Observations Level Summary over Type of Plants" = 5), bold = T, font_size = 18)
st1  
#--------------------------------------------
save_kable(st1, file = "../report/table_1.png", zoom = 4, keep_tex = T)
```


```{r, echo = F, eval=FALSE}
pp_data_unique <- pp_data %>% group_by(plant) %>% 
  summarise(mean.comp.plant = mean(complete))

pp_data_unique <- merge(pp_data, pp_data_unique, by = "plant")
pp_data_unique <- pp_data_unique[which(!duplicated(pp_data$plant) == T),]

#--------------------------------------------
# type_of_p
our_summary2 <-
  list("Plant" =
       list("Unique Names of Plants" = ~ length(unique(plant))),
      "Electricity generated per month" =
       list("Electricity generated per month" = ~ print(""),
            # "min"       = ~ min(complete),
            "median"    = ~ median(complete),
            # "max"       = ~ max(complete),
            "mean (sd)" = ~ qwraps2::mean_sd(mean.comp.plant)),
       "Plant Capacity" =
       list("Plant Capacity" = ~ print(""),
            # "min"       = ~ min(capacity),
            "median"    = ~ median(capacity),
            # "max"       = ~ max(capacity),
            "mean (sd)" = ~ qwraps2::mean_sd(capacity)),
       "City" =
       list("Unique Names of Cities" = ~ length(unique(area3))),
      "Owned by Big-Five"  =
       list("Owned by Big-Five" = ~ print(""),
            "Owned"     = ~ sum(big_five))
)


st2 <- summary_table(group_by(pp_data_unique, type_of_p), our_summary2) %>%
  kbt() %>%
  add_header_above(header = c("Plants Level Summary over Type of Plants" = 5), 
                   bold = T, font_size = 18)

save_kable(st2, file = "../report/table_2.png", keep_tex = T, zoom = 4)
#--------------------------------------------
# city

our_summary3 <-
  list("Plant" =
       list("Unique Names of Plants" = ~ length(unique(plant))),
      "Electricity generated per month" =
       list("Electricity generated per month" = ~ print(""),
            # "min"       = ~ min(complete),
            "median"    = ~ median(complete),
            # "max"       = ~ max(complete),
            "mean (sd)" = ~ qwraps2::mean_sd(mean.comp.plant)),
       "Plant Capacity" =
       list("Plant Capacity" = ~ print(""),
            # "min"       = ~ min(capacity),
            "median"    = ~ median(capacity),
            # "max"       = ~ max(capacity),
            "mean (sd)" = ~ qwraps2::mean_sd(capacity)),
       "City" =
       list("Unique Names of Cities" = ~ length(unique(area3))),
       "Owned by Big-Five"  =
       list("Owned by Big-Five" = ~ print(""),
            "Owned"     = ~ sum(big_five))
)

st3 <- summary_table(group_by(pp_data_unique, city), our_summary3) %>%
  kbt %>%
  add_header_above(header = c("Plants Level Summary over City Type" = 3), bold = T , font_size = 18)
save_kable(st3, file = "../report/table_3.png", keep_tex = T, zoom = 4)
#--------------------------------------------

# area3
our_summary4 <-
  list("Plant" =
       list("Unique Names of Plants" = ~ length(unique(plant))),
      "Electricity generated per month" =
       list("Electricity generated per month" = ~ print(""),
            # "min"       = ~ min(complete),
            "median"    = ~ median(complete),
            # "max"       = ~ max(complete),
            "mean (sd)" = ~ qwraps2::mean_sd(mean.comp.plant)),
       "Plant Capacity" =
       list("Plant Capacity" = ~ print(""),
            # "min"       = ~ min(capacity),
            "median"    = ~ median(capacity),
            # "max"       = ~ max(capacity),
            "mean (sd)" = ~ qwraps2::mean_sd(capacity)),
      "Owned by Big-Five"  =
       list("Owned by Big-Five" = ~print("") ,
            "Owned"     = ~ sum(big_five))
)

st4 <- summary_table(group_by(pp_data_unique, area3), our_summary4)  %>%  kbt %>%
  add_header_above(header = c("Plants Level Summary over Area" = 12), bold = T,  font_size = 18)
save_kable(st4, file = "../report/table_4.png", keep_tex = T, zoom = 4)
```

#--------------------------------------------

## 2. corr data

```{r, echo = F}
# pp_data %>% names
st_options(plain.ascii = FALSE)
# print(dfSummary(pp_data[, -c(1,2,3,6,7,8,9,10,11,12,14,20, 21)], style = 'grid', graph.magnif = 0.75, 
#           valid.col = FALSE, tmp.img.dir = "/tmp"), method = 'render')
```


```{r, echo = F}
# print(dfSummary(tobacco, graph.magnif = 0.75))
pp_data[, -c(1,2,3,6,7,8,9,10,11,12,13, 14, 20, 21)] %>% str
mcor <- cor(pp_data[, -c(1,2,3,6,7,8,9,10,11,12,13, 14,19,20, 21)])
upper <- mcor

upper[upper.tri(mcor)] <- "" 
upper <- data.frame(upper)

library(xtable)
xtable <- xtable(upper) %>% data.frame()

st5 <- xtable(upper) %>% kbt %>%
  add_header_above(header = c("Variable correlations" = 9), bold = T, font_size = 18)


save_kable(st5, file = "../report/table_5.png", keep_tex = T, zoom = 4)
# print(xtable(upper), type = "html", method = "render")

# corstars(mtcars[,1:7], result="html")
```